datasource-config:
    tenants:
      ajio:
        url: jdbc:h2:mem:ajio;DB_CLOSE_DELAY=-1
        username: sa
        password: password
        driver-class-name: org.h2.Driver
      clovia:
        url: jdbc:h2:mem:clovia;DB_CLOSE_DELAY=-1
        username: sa
        password: password
        driver-class-name: org.h2.Driver

server:
  port: 8080

default:
  tenant: ajio

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.SQL: DEBUG


hibernate:
  format_sql: true


spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console # Default path